[build]
  command = "pip install -r requirements.txt"
  publish = "web"

[functions]
  included_files = ["api/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200